### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by varlesh** [PapirusDevelopmentTeam/adapta-kde#5]
- [x] Fix Splash on L&F
- [x] Add `X-KPackage-Dependencies` on L&F
- [x] Fix defaults on L&F
- [x] MakeFile
- [x] Update README
- [x] Create PPA repo and build a package
- [x] Add installation script
- [x] Create GitHub release

**Comment by varlesh** [comment]
@SmartFinn Hi, for install maybe make only and packages?

**Comment by SmartFinn** [comment]
@varlesh Привет!

Скрипт написать ничего не стоит (если только один, а не кучу), а удобства для пользователей и для тестирования в виртуалках добавляет неоценимо.

**Comment by varlesh** [comment]
@SmartFinn Ну ладно, как скажешь ))

**Comment by SmartFinn** [comment]
@varlesh ошибкой было все ложить по разным PPA, arc-kde и adapta-kde оба зависят от Kvantum и papirus-icon-theme. Может стоит собрать их вместе в Papirus PPA и не морочить голову себе с переносом пакетов, и пользователям с установкой 2-3 отдельных PPA.

**Comment by varlesh** [comment]
@SmartFinn Привет. Да, так лучше.

**Comment by SmartFinn** [comment]
@varlesh ок, тогда adapta-kde PPA уничтожаю, Kvantum и Yakuake копирую в Papirus PPA. Туда же собирю adapta-kde. arc-kde собираю пока в оба места, но в arc-kde PPA вешаю плашку что использовать его не стоит. Вроде ничего не ломаем таким образом.

**Comment by varlesh** [comment]
@SmartFinn Релиз Papirus делать или ты еще планируешь с папками заморочиться?

**Comment by SmartFinn** [comment]
@varlesh потерпи пока, попробую за дня 3 доделать. Так конфликтов поднакопилось...

**Comment by varlesh** [comment]
ок

**Comment by varlesh** [comment]
релизнул
